### ISSUE TITLE
I18n::MissingInterpolationArgument bug

### ISSUE THREAD

**Issue by ghepting** [mattetti/i18n#6]
Given the following yaml strings with interpolation variables:

```
en:
  test1: "Buy this thing now for %{price}"
  test2: "Buy this thing now for %{price} plus %{extra_price}"
```

each of the follow specs should pass, but do not:

```
require 'i18n'
require 'rspec'

I18n.load_path << 'en.yml'

RSpec.describe '#missing_interpolation_argument_handler' do
  it 'raises an exception if 0 of 1 is passed' do
    expect { I18n.translate('test1') }.to raise_error(I18n::MissingInterpolationArgument)
  end
  it 'does not raise an exception if 1 of 1 is passed' do
    expect { I18n.translate('test1', price: '$5') }.not_to raise_error
  end
  it 'raises an exception if 0 of 2 is passed' do
    expect { I18n.translate('test2') }.to raise_error(I18n::MissingInterpolationArgument)
  end
  it 'raises an exception if 1 of 2 is passed' do
    expect { I18n.translate('test2', price: '$5') }.to raise_error(I18n::MissingInterpolationArgument)
  end
  it 'does not raise an exception if 2 of 2 is passed' do
    expect { I18n.translate('test2', price: '$5', extra_price: 'Your soul') }.not_to raise_error
  end
end
```

```
~/Development/test master *+ rspec test.rb
F.F..

Failures:

  1) #missing_interpolation_argument_handler raises an exception if 0 of 1 is passed
     Failure/Error: expect { I18n.translate('test1') }.to raise_error(I18n::MissingInterpolationArgument)
       expected I18n::MissingInterpolationArgument but nothing was raised
     # ./test.rb:8:in `block (2 levels) in <top (required)>'

  2) #missing_interpolation_argument_handler raises an exception if 0 of 2 is passed
     Failure/Error: expect { I18n.translate('test2') }.to raise_error(I18n::MissingInterpolationArgument)
       expected I18n::MissingInterpolationArgument but nothing was raised
     # ./test.rb:14:in `block (2 levels) in <top (required)>'

Finished in 0.02405 seconds (files took 0.08735 seconds to load)
5 examples, 2 failures

Failed examples:

rspec ./test.rb:7 # #missing_interpolation_argument_handler raises an exception if 0 of 1 is passed
rspec ./test.rb:13 # #missing_interpolation_argument_handler raises an exception if 0 of 2 is passed
```

This shows that no exceptions are raised when _no_ interpolation variables are passed. This is not the behavior I would except, and is resulting the interpolation content being output.

**Comment by ghepting** [comment]
Valid usage example:

`t('test1', price: '$5')` => `Buy this thing now for $5`

Erroneous usage example:

`t('test1')` => `Buy this thing now for %{price}`

Erroneous usage example that actually raises an error:

`t('test2', price: '$5')` => raises `I18n::MissingInterpolationArgument`

Valid usage example:

`t('test2', price: '$5', extra_price: 'Your soul')` => `Buy this thing now for $5 plus Your soul`
